### ISSUE TITLE
Re-generate the docs/markdown files

### ISSUE THREAD

**Issue by tanius** [jansorg/tom#33]
The auto-generated documentation in `docs/markdown` currently [says](https://github.com/jansorg/tom/blob/7ebbdf207c7155dfa086f057940f81035f7acf18/docs/markdown/tom_config.md):

>      -c, --config string     config file (default is $HOME/.gotime.yaml)
>           --data-dir string   data directory (default is $HOME/.gotime)

That seems outdated because `tom --help` says:

>     Flags:
>       -c, --config string     config file (default is $HOME/.tom/tom.yaml)
>           --data-dir string   data directory (default is $HOME/.tom)

and the data dir is indeed found under `$HOME/.tom` in this version (tom 0.5.0 on Ubuntu 18.10 here).

**Comment by jansorg** [comment]
Done and added in the release script
