### ISSUE TITLE
Use a consistent date format in reports

### ISSUE THREAD

**Issue by tanius** [jansorg/tom#52]
I just noticed the following in HTML reports generated via `tom-ui`, which are generated via a `tom` command (I think), so I'm reporting this here as a `tom` issue. Namely, the reports will contain a report that uses "Template: Time Entries" and also has "Template: Show summary: yes" set, will contain a summary with a date format in mm/dd/yy notation, for example:

```
Time range: 3/1/20 - 3/31/20
Tracked time: 28:34
```

However time entries will use the yyyy-mm-dd date format in the "Date column".

It would be preferable to use a consistent date format, preferably the international ISO date format yyyy-mm-dd, not the botched and illogical U.S. American date format currently employed in the summary table. Even better of course would be for date formats to respect the system's localization settings. (Maybe one of the two date formats seen does that already, I didn't test.)

**Comment by jansorg** [comment]
Fixed for the next update. The default date and time format will follow the locale (en_US and de_DE supported).
There'll be a new commandline switch to use the iso date format instead.

**Comment by jansorg** [comment]
Fixed with 0.12
